export type Forms = 'command' | 'query' | 'both';
export type Mutability = 'read' | 'setup' | 'destructive';
export type Response = 'text' | 'binary' | 'none';

export interface CommandEntry {
	id: string;
	subsystem: string;
	forms: Forms;
	mutability: Mutability;
	response: Response;
	owner: string;
	tools: readonly string[];
	// The reason one form or one value of the row is not covered. Rendered into docs/command-coverage.md so a
	// reader finds it without reading the source.
	note?: string;
}

type Tweak = Partial<Pick<CommandEntry, 'mutability' | 'response' | 'owner' | 'tools' | 'note'>>;
type Row = [id: string, forms: Forms, tweak?: Tweak];

const done = (module: string, ...tools: string[]): Tweak => ({
	owner: `devices/oscilloscope-scpi/${module}`,
	tools,
});
const destructive: Tweak = { mutability: 'destructive' };
const partial = (tweak: Tweak, note: string): Tweak => ({ ...tweak, note });
const settings = done('tools/system', 'get_system_settings', 'configure_system_settings');
const lan = done('tools/system', 'get_lan_configuration', 'configure_lan');
const storage = done('tools/system', 'get_network_storage', 'configure_network_storage');
const acquisition = done('tools/acquisition', 'get_acquisition', 'configure_acquisition');
const timebase = done('tools/timebase', 'get_timebase', 'configure_timebase');
const channel = done('tools/channel', 'get_channel', 'configure_channel');
const waveform = done('tools/waveform', 'get_waveform');
const trigger = done('tools/trigger', 'get_trigger', 'configure_trigger');
const runControl = done('tools/trigger', 'configure_trigger_mode');
const sweep = done('tools/trigger', 'get_trigger', 'configure_trigger_mode');
const measureSetup = done('tools/measure', 'get_measurement_setup', 'configure_measurement_setup');
const measureMode = done(
	'tools/measure',
	'get_measurement_setup',
	'configure_measurement_setup',
	'measure',
	'configure_advanced_measurement',
	'measure_delay',
);
const measureGate = done('tools/measure', 'get_measurement_gate', 'configure_measurement_gate');
const measureStats = done('tools/measure', 'get_measurement_statistics', 'configure_measurement_statistics');
const advancedItem = done(
	'tools/measure',
	'list_measurements',
	'get_measurement_statistics',
	'configure_advanced_measurement',
	'measure_delay',
);
const simpleSource = done(
	'tools/measure',
	'get_measurement_setup',
	'configure_measurement_setup',
	'measure',
	'read_measurement',
);
const simpleValue = done('tools/measure', 'measure', 'read_measurement');
const clearMeasurements = { ...done('tools/measure', 'clear_measurements'), ...destructive };
const counter = done('tools/counter', 'get_counter', 'configure_counter');
const counterMode = done('tools/counter', 'get_counter', 'configure_counter', 'reset_counter');
const counterReset = { ...done('tools/counter', 'reset_counter'), ...destructive };
const memory = done('tools/storage', 'get_memory', 'configure_memory');
const memoryImport = { ...done('tools/storage', 'import_memory'), ...destructive };
const reference = done('tools/storage', 'get_reference', 'configure_reference');
const referenceData = { ...reference, ...destructive };
const setupSave = { ...done('tools/storage', 'save_panel_setup'), ...destructive };
const setupRecall = { ...done('tools/storage', 'recall_panel_setup'), ...destructive };
const waveformFile = { ...done('tools/storage', 'save_waveform_file'), ...destructive };
const search = done('tools/search', 'get_search', 'configure_search');
const searchState = done('tools/search', 'get_search', 'configure_search', 'read_search_events');
const searchEvents = done('tools/search', 'read_search_events');
const searchCopy = { ...done('tools/search', 'copy_search_settings'), ...destructive };
const maskTest = done('tools/mask', 'get_mask_test', 'configure_mask_test');
const maskState = done('tools/mask', 'get_mask_test', 'configure_mask_test', 'read_mask_test_result');
const maskCount = done('tools/mask', 'read_mask_test_result');
const maskReset = { ...done('tools/mask', 'reset_mask_test'), ...destructive };
const maskCreate = { ...done('tools/mask', 'create_mask'), ...destructive };
const maskLoad = { ...done('tools/mask', 'load_mask'), ...destructive };
const cursor = done('tools/cursor', 'get_cursors', 'configure_cursors');
const decode = done('tools/decode', 'get_decode', 'configure_decode');
const decodeBus = done('tools/decode', 'get_decode', 'configure_decode', 'read_decode_result');
const decodeResult = done('tools/decode', 'read_decode_result');
const decodeCopy = { ...done('tools/decode', 'copy_decode_settings'), ...destructive };
const cursorState = done('tools/cursor', 'get_cursors', 'configure_cursors', 'measure_cursors');
const cursorDelta = done('tools/cursor', 'measure_cursors');
const dvm = done('tools/dvm', 'get_dvm_reading', 'configure_dvm');
const digital = done('tools/digital', 'get_digital', 'configure_digital');
const digitalRead = done('tools/digital', 'get_digital');
const display = done('tools/display', 'get_display', 'configure_display');
const history = done('tools/history', 'get_history', 'configure_history');
const math = done('tools/function', 'get_math', 'configure_math');
const mathFft = done('tools/function', 'get_math', 'configure_math', 'get_fft', 'configure_fft');
const fft = done('tools/function', 'get_fft', 'configure_fft');
const fftLevel = done('tools/function', 'get_fft', 'configure_fft', 'autoset_fft');
const fftSearch = done('tools/function', 'get_fft', 'configure_fft', 'read_fft_peaks');
const generator = done('tools/wgen', 'get_waveform_generator', 'configure_waveform_generator');
const generatorStore = done('tools/wgen', 'get_waveform_generator');
const meter = done('tools/meter', 'configure_meter');
const meterFunction = done('tools/meter', 'read_meter', 'configure_meter');
const meterValue = done('tools/meter', 'read_meter');
// A MEASure query returns the function to its default parameters before it answers, so the row writes even though
// its only form is a query, and the tool that owns it is mutating.
const meterMeasure: Tweak = { ...done('tools/meter', 'measure_meter'), mutability: 'setup' };

function subsystem(name: string, rows: Row[]): CommandEntry[] {
	return rows.map(([id, forms, tweak]) => ({
		id,
		subsystem: name,
		forms,
		mutability: forms === 'query' ? 'read' : 'setup',
		response: forms === 'command' ? 'none' : 'text',
		owner: '',
		tools: [],
		...tweak,
	}));
}

// Transcribed from the SDS Series Programming Guide EN11F, one row per documented command section, in guide order.
// `forms` comes from the COMMAND SYNTAX and QUERY SYNTAX blocks of a section rather than from its heading, because
// three headings contradict their own syntax blocks. The WGEN and METEr sections are the one deliberate exception to
// the driver's leading-colon wire style: neither group prints a leading colon and both are transcribed as printed.
// Every misprint the guide carries, what is transcribed instead and the evidence for it are listed in
// docs/hardware-verification.md, "EN11F transcription ledger".
export const manifest: readonly CommandEntry[] = [
	...subsystem('common', [
		['*IDN', 'query', done('tools/common', 'identify')],
		['*OPC', 'query', done('tools/common', 'wait_until_complete')],
		['*RST', 'command', { ...destructive, ...done('tools/common', 'reset_scope') }],
	]),
	...subsystem('root', [
		[':AUToset', 'command', { ...destructive, ...done('tools/root', 'autoset_scope') }],
		[':PRINt', 'query', { response: 'binary', ...done('tools/root', 'capture_screenshot') }],
		[':FORMat:DATA', 'both', done('tools/root', 'get_data_format', 'configure_data_format')],
	]),
	...subsystem('acquire', [
		[':ACQuire:AMODe', 'both', acquisition],
		[':ACQuire:CSWeep', 'command', { ...done('tools/acquisition', 'clear_sweeps'), ...destructive }],
		[':ACQuire:INTerpolation', 'both', acquisition],
		[':ACQuire:MMANagement', 'both', acquisition],
		[':ACQuire:MODE', 'both', acquisition],
		[':ACQuire:MDEPth', 'both', acquisition],
		[':ACQuire:NUMAcq', 'query', done('tools/acquisition', 'get_acquisition')],
		[':ACQuire:POINts', 'query', done('tools/acquisition', 'get_acquisition', 'get_waveform')],
		// Documented for the SDS2000X Plus alone, so scope.ts owns the query the handshake and both tools read it with.
		[':ACQuire:RESolution', 'both', done('scope', 'identify', 'get_acquisition', 'configure_acquisition')],
		[':ACQuire:SEQuence', 'both', acquisition],
		[':ACQuire:SEQuence:COUNt', 'both', acquisition],
		[':ACQuire:SRATe', 'both', acquisition],
		[':ACQuire:TYPE', 'both', acquisition],
	]),
	...subsystem('channel', [
		[':CHANnel:REFerence', 'both', channel],
		[':CHANnel<n>:BWLimit', 'both', channel],
		[':CHANnel<n>:COUPling', 'both', channel],
		[':CHANnel<n>:IMPedance', 'both', channel],
		[':CHANnel<n>:INVert', 'both', channel],
		[':CHANnel<n>:LABel', 'both', channel],
		[':CHANnel<n>:LABel:TEXT', 'both', channel],
		[':CHANnel<n>:OFFSet', 'both', channel],
		[':CHANnel<n>:PROBe', 'both', channel],
		[':CHANnel<n>:SCALe', 'both', channel],
		[':CHANnel<n>:SKEW', 'both', channel],
		[':CHANnel<n>:SWITch', 'both', channel],
		[':CHANnel<n>:UNIT', 'both', channel],
		[':CHANnel<n>:VISible', 'both', channel],
	]),
	...subsystem('counter', [
		[':COUNter', 'both', counter],
		[':COUNter:LEVel', 'both', counter],
		[':COUNter:MODE', 'both', counterMode],
		[':COUNter:SOURce', 'both', counter],
		[':COUNter:STATistics', 'both', counter],
		[':COUNter:STATistics:RESet', 'command', counterReset],
		[':COUNter:TOTalizer:GATE', 'both', counter],
		[':COUNter:TOTalizer:GATE:LEVel', 'both', counter],
		[':COUNter:TOTalizer:GATE:SLOPe', 'both', counter],
		[':COUNter:TOTalizer:GATE:TYPE', 'both', counter],
		[':COUNter:TOTalizer:RESet', 'command', counterReset],
		[':COUNter:TOTalizer:SLOPe', 'both', counter],
	]),
	...subsystem('cursor', [
		[':CURSor', 'both', cursorState],
		[':CURSor:TAGStyle', 'both', cursor],
		[':CURSor:IXDelta', 'query', cursorDelta],
		[':CURSor:MITem', 'both', cursor],
		[':CURSor:MODE', 'both', cursorState],
		[':CURSor:SOURce1', 'both', cursorState],
		[':CURSor:SOURce2', 'both', cursorState],
		[':CURSor:X1', 'both', cursorState],
		[':CURSor:X2', 'both', cursorState],
		[':CURSor:XDELta', 'query', cursorDelta],
		[':CURSor:XREFerence', 'both', cursor],
		[':CURSor:Y1', 'both', cursorState],
		[':CURSor:Y2', 'both', cursorState],
		[':CURSor:YDELta', 'query', cursorDelta],
		[':CURSor:YREFerence', 'both', cursor],
	]),
	...subsystem('decode', [
		[':DECode', 'both', decodeBus],
		[':DECode:LIST', 'both', decode],
		[':DECode:LIST:LINE', 'both', decode],
		[':DECode:LIST:SCRoll', 'both', decode],
		[':DECode:BUS<n>', 'both', decodeBus],
		[':DECode:BUS<n>:COPY', 'command', decodeCopy],
		[':DECode:BUS<n>:FORMat', 'both', decodeBus],
		[':DECode:BUS<n>:PROTocol', 'both', decodeBus],
		[':DECode:BUS<n>:RESult', 'query', decodeResult],
		[':DECode:BUS<n>:IIC:RWBit', 'both', decode],
		[':DECode:BUS<n>:IIC:SCLSource', 'both', decode],
		[':DECode:BUS<n>:IIC:SCLThreshold', 'both', decode],
		[':DECode:BUS<n>:IIC:SDASource', 'both', decode],
		[':DECode:BUS<n>:IIC:SDAThreshold', 'both', decode],
		[':DECode:BUS<n>:SPI:BITorder', 'both', decode],
		[':DECode:BUS<n>:SPI:CLKSource', 'both', decode],
		[':DECode:BUS<n>:SPI:CLKThreshold', 'both', decode],
		[':DECode:BUS<n>:SPI:CSSource', 'both', decode],
		[':DECode:BUS<n>:SPI:CSThreshold', 'both', decode],
		[':DECode:BUS<n>:SPI:CSTYpe', 'both', decode],
		[':DECode:BUS<n>:SPI:DLENgth', 'both', decode],
		[':DECode:BUS<n>:SPI:LATChedge', 'both', decode],
		[':DECode:BUS<n>:SPI:MISOSource', 'both', decode],
		[':DECode:BUS<n>:SPI:MISOThreshold', 'both', decode],
		[':DECode:BUS<n>:SPI:MOSISource', 'both', decode],
		[':DECode:BUS<n>:SPI:MOSIThreshold', 'both', decode],
		[':DECode:BUS<n>:SPI:NCSSource', 'both', decode],
		[':DECode:BUS<n>:SPI:NCSThreshold', 'both', decode],
		[':DECode:BUS<n>:UART:BAUD', 'both', decode],
		[':DECode:BUS<n>:UART:BITorder', 'both', decode],
		[':DECode:BUS<n>:UART:DLENgth', 'both', decode],
		[':DECode:BUS<n>:UART:IDLE', 'both', decode],
		[':DECode:BUS<n>:UART:PARity', 'both', decode],
		[':DECode:BUS<n>:UART:RXSource', 'both', decode],
		[':DECode:BUS<n>:UART:RXThreshold', 'both', decode],
		[':DECode:BUS<n>:UART:STOP', 'both', decode],
		[':DECode:BUS<n>:UART:TXSource', 'both', decode],
		[':DECode:BUS<n>:UART:TXThreshold', 'both', decode],
		[':DECode:BUS<n>:CAN:BAUD', 'both', decode],
		[':DECode:BUS<n>:CAN:SOURce', 'both', decode],
		[':DECode:BUS<n>:CAN:THReshold', 'both', decode],
		[':DECode:BUS<n>:LIN:BAUD', 'both', decode],
		[':DECode:BUS<n>:LIN:SOURce', 'both', decode],
		[':DECode:BUS<n>:LIN:THReshold', 'both', decode],
		[':DECode:BUS<n>:FLEXray:BAUD', 'both', decode],
		[':DECode:BUS<n>:FLEXray:SOURce', 'both', decode],
		[':DECode:BUS<n>:FLEXray:THReshold', 'both', decode],
		[':DECode:BUS<n>:CANFd:BAUDData', 'both', decode],
		[':DECode:BUS<n>:CANFd:BAUDNominal', 'both', decode],
		[':DECode:BUS<n>:CANFd:SOURce', 'both', decode],
		[':DECode:BUS<n>:CANFd:THReshold', 'both', decode],
		[':DECode:BUS<n>:IIS:ANNotate', 'both', decode],
		[':DECode:BUS<n>:IIS:AVARiant', 'both', decode],
		[':DECode:BUS<n>:IIS:BCLKSource', 'both', decode],
		[':DECode:BUS<n>:IIS:BCLKThreshold', 'both', decode],
		[':DECode:BUS<n>:IIS:BITorder', 'both', decode],
		[':DECode:BUS<n>:IIS:DLENgth', 'both', decode],
		[':DECode:BUS<n>:IIS:DSource', 'both', decode],
		[':DECode:BUS<n>:IIS:DTHReshold', 'both', decode],
		[':DECode:BUS<n>:IIS:LATChedge', 'both', decode],
		[':DECode:BUS<n>:IIS:LCH', 'both', decode],
		[':DECode:BUS<n>:IIS:SBIT', 'both', decode],
		[':DECode:BUS<n>:IIS:WSSource', 'both', decode],
		[':DECode:BUS<n>:IIS:WSTHreshold', 'both', decode],
		[':DECode:BUS<n>:M1553:LTHReshold', 'both', decode],
		[':DECode:BUS<n>:M1553:SOURce', 'both', decode],
		[':DECode:BUS<n>:M1553:UTHReshold', 'both', decode],
		[':DECode:BUS<n>:SENT:SOURce', 'both', decode],
		[':DECode:BUS<n>:SENT:THReshold', 'both', decode],
		[':DECode:BUS<n>:SENT:FORMat', 'both', decode],
		[':DECode:BUS<n>:SENT:CLOCk', 'both', decode],
		[':DECode:BUS<n>:SENT:TOLerance', 'both', decode],
		[':DECode:BUS<n>:SENT:IDLE', 'both', decode],
		[':DECode:BUS<n>:SENT:LENGth', 'both', decode],
		[':DECode:BUS<n>:SENT:CRC', 'both', decode],
		[':DECode:BUS<n>:SENT:PPULse', 'both', decode],
		[':DECode:BUS<n>:MANChester:SOURce', 'both', decode],
		[':DECode:BUS<n>:MANChester:THReshold', 'both', decode],
		[':DECode:BUS<n>:MANChester:BAUD', 'both', decode],
		[':DECode:BUS<n>:MANChester:POLarity', 'both', decode],
		[':DECode:BUS<n>:MANChester:IDLE', 'both', decode],
		[':DECode:BUS<n>:MANChester:IBITs', 'both', decode],
		[':DECode:BUS<n>:MANChester:STARt', 'both', decode],
		[':DECode:BUS<n>:MANChester:SSIZe', 'both', decode],
		[':DECode:BUS<n>:MANChester:HSIZe', 'both', decode],
		[':DECode:BUS<n>:MANChester:TSIZe', 'both', decode],
		[':DECode:BUS<n>:MANChester:WSIZe', 'both', decode],
		[':DECode:BUS<n>:MANChester:DSIZe', 'both', decode],
		[':DECode:BUS<n>:MANChester:DISPlay', 'both', decode],
		[':DECode:BUS<n>:MANChester:BITorder', 'both', decode],
	]),
	...subsystem('digital', [
		[':DIGital', 'both', digital],
		[':DIGital:ACTive', 'both', digital],
		[':DIGital:BUS<n>:DISPlay', 'both', digital],
		[':DIGital:BUS<n>:DEFault', 'command', done('tools/digital', 'configure_digital')],
		[':DIGital:BUS<n>:FORMat', 'both', digital],
		[':DIGital:BUS<n>:MAP', 'both', digital],
		[':DIGital:D<d>', 'both', digital],
		[':DIGital:HEIGht', 'both', digital],
		[':DIGital:LABel<d>', 'both', digital],
		[':DIGital:POINts', 'query', digitalRead],
		[':DIGital:POSition', 'both', digital],
		[':DIGital:SKEW', 'both', digital],
		[':DIGital:SRATe', 'query', digitalRead],
		[':DIGital:THReshold<n>', 'both', digital],
	]),
	...subsystem('display', [
		[':DISPlay:AXIS', 'both', display],
		[':DISPlay:AXIS:MODE', 'both', display],
		[':DISPlay:BACKlight', 'both', display],
		[':DISPlay:CLEar', 'command', { ...done('tools/display', 'clear_display'), ...destructive }],
		[':DISPlay:COLor', 'both', display],
		[':DISPlay:GRATicule', 'both', display],
		[':DISPlay:GRIDstyle', 'both', display],
		[':DISPlay:INTensity', 'both', display],
		[':DISPlay:MENU', 'both', display],
		[':DISPlay:MENU:HIDE', 'both', display],
		[':DISPlay:PERSistence', 'both', display],
		// Documented for the SHS800X/SHS1000X alone (p. 219), so any other model is refused rather than asked.
		[':DISPlay:TRANsparence', 'both', display],
		[':DISPlay:TYPE', 'both', display],
	]),
	...subsystem('dvm', [
		[':DVM', 'both', dvm],
		[':DVM:ALARm', 'both', dvm],
		[':DVM:ARANge', 'both', dvm],
		[':DVM:CURRent', 'query', done('tools/dvm', 'get_dvm_reading')],
		[':DVM:HOLD', 'both', dvm],
		[':DVM:MODE', 'both', dvm],
		[':DVM:SOURce', 'both', dvm],
	]),
	...subsystem('function', [
		[':FUNCtion:FFTDisplay', 'both', fft],
		[':FUNCtion:GVALue', 'both', math],
		[
			':FUNCtion<x>',
			'both',
			done('tools/function', 'get_math', 'configure_math', 'get_fft', 'configure_fft', 'get_waveform'),
		],
		[':FUNCtion<x>:AVERage:NUM', 'both', math],
		[':FUNCtion<x>:DIFF:DX', 'both', math],
		[':FUNCtion<x>:ERES:BITS', 'both', math],
		[':FUNCtion<x>:FFT:AUToset', 'command', done('tools/function', 'autoset_fft')],
		[':FUNCtion<x>:FFT:HCENter', 'both', fftLevel],
		[':FUNCtion<x>:FFT:HSCale', 'query', done('tools/function', 'get_fft')],
		[':FUNCtion<x>:FFT:SPAN', 'both', fftLevel],
		[':FUNCtion<x>:FFT:LOAD', 'both', fft],
		[':FUNCtion<x>:FFT:MODE', 'both', done('tools/function', 'get_fft', 'configure_fft', 'reset_fft')],
		[':FUNCtion<x>:FFT:POINts', 'both', fft],
		[':FUNCtion<x>:FFT:RESET', 'command', { ...done('tools/function', 'reset_fft'), ...destructive }],
		[':FUNCtion<x>:FFT:RLEVel', 'both', fftLevel],
		[':FUNCtion<x>:FFT:SCALe', 'both', fftLevel],
		[':FUNCtion<x>:FFT:SEARch', 'both', fftSearch],
		[':FUNCtion<x>:FFT:SEARch:EXCursion', 'both', fft],
		[':FUNCtion<x>:FFT:SEARch:RESult', 'query', done('tools/function', 'read_fft_peaks')],
		[':FUNCtion<x>:FFT:SEARch:THReshold', 'both', fft],
		[':FUNCtion<x>:FFT:UNIT', 'both', fftSearch],
		[':FUNCtion<x>:FFT:WINDow', 'both', fft],
		[':FUNCtion<x>:FILTer:TYPe', 'both', math],
		[':FUNCtion<x>:FILTer:HFRequency', 'both', math],
		[':FUNCtion<x>:FILTer:LFRequency', 'both', math],
		[':FUNCtion<x>:INTegrate:GATE', 'both', math],
		[':FUNCtion<x>:INTegrate:OFFSet', 'both', math],
		[':FUNCtion<x>:INTErpolate:COEF', 'both', math],
		[':FUNCtion<x>:INVert', 'both', math],
		[':FUNCtion<x>:LABel', 'both', math],
		[':FUNCtion<x>:LABel:TEXT', 'both', math],
		[':FUNCtion<x>:MAXHold:SWeeps', 'both', math],
		[':FUNCtion<x>:MINHold:SWeeps', 'both', math],
		[':FUNCtion<x>:OPERation', 'both', mathFft],
		[':FUNCtion<x>:POSition', 'both', math],
		[':FUNCtion<x>:SCALe', 'both', math],
		[':FUNCtion<x>:SOURce1', 'both', mathFft],
		[':FUNCtion<x>:SOURce2', 'both', math],
	]),
	...subsystem('history', [
		[':HISTORy', 'both', history],
		[':HISTORy:FRAMe', 'both', history],
		[':HISTORy:INTERval', 'both', history],
		[':HISTORy:LIST', 'both', history],
		[':HISTORy:PLAY', 'both', history],
		[':HISTORy:TIME', 'query', done('tools/history', 'get_history')],
	]),
	...subsystem('measure', [
		[':MEASure', 'both', measureMode],
		[':MEASure:ADVanced:CLEar', 'command', clearMeasurements],
		[
			':MEASure:ADVanced:LINenumber',
			'both',
			done(
				'tools/measure',
				'get_measurement_setup',
				'configure_measurement_setup',
				'list_measurements',
				'get_measurement_statistics',
			),
		],
		[':MEASure:ADVanced:P<n>', 'both', advancedItem],
		[':MEASure:ADVanced:P<n>:SOURce1', 'both', advancedItem],
		[':MEASure:ADVanced:P<n>:SOURce2', 'both', advancedItem],
		[':MEASure:ADVanced:P<n>:STATistics', 'query', done('tools/measure', 'get_measurement_statistics')],
		[':MEASure:ADVanced:P<n>:TYPE', 'both', advancedItem],
		[':MEASure:ADVanced:P<n>:VALue', 'query', advancedItem],
		[':MEASure:ADVanced:STATistics', 'both', measureStats],
		[':MEASure:ADVanced:STATistics:AIMLimit', 'both', measureStats],
		[':MEASure:ADVanced:STATistics:HISTOGram', 'both', measureStats],
		[':MEASure:ADVanced:STATistics:MAXCount', 'both', measureStats],
		[
			':MEASure:ADVanced:STATistics:RESet',
			'command',
			{ ...done('tools/measure', 'configure_measurement_statistics'), ...destructive },
		],
		[':MEASure:ADVanced:STYLe', 'both', measureSetup],
		[':MEASure:ASTRategy', 'both', measureSetup],
		[':MEASure:ASTRategy:BASE', 'both', measureSetup],
		[':MEASure:ASTRategy:TOP', 'both', measureSetup],
		[':MEASure:GATE', 'both', measureGate],
		[':MEASure:GATE:GA', 'both', measureGate],
		[':MEASure:GATE:GB', 'both', measureGate],
		[':MEASure:MODE', 'both', measureMode],
		[':MEASure:SIMPle:CLEar', 'command', clearMeasurements],
		[':MEASure:SIMPle:ITEM', 'command', done('tools/measure', 'measure')],
		[':MEASure:SIMPle:SOURce', 'both', simpleSource],
		[':MEASure:SIMPle:VALue', 'query', simpleValue],
		[':MEASure:THReshold:SOURce', 'both', measureSetup],
		[':MEASure:THReshold:TYPE', 'both', measureSetup],
		[':MEASure:THReshold:ABSolute', 'both', measureSetup],
		[':MEASure:THReshold:PERCent', 'both', measureSetup],
	]),
	...subsystem('memory', [
		[':MEMory<m>:HORizontal:POSition', 'both', memory],
		[':MEMory<m>:HORizontal:SCALe', 'both', memory],
		[':MEMory<m>:HORizontal:SYNC', 'both', memory],
		[':MEMory<m>:IMPort', 'command', memoryImport],
		[':MEMory<m>:LABel', 'both', memory],
		[':MEMory<m>:LABel:TEXT', 'both', memory],
		[':MEMory<m>:SWITch', 'both', memory],
		[':MEMory<m>:VERTical:POSition', 'both', memory],
		[':MEMory<m>:VERTical:SCALe', 'both', memory],
	]),
	...subsystem('mtest', [
		[':MTESt', 'both', maskState],
		[':MTESt:COUNt', 'query', maskCount],
		[':MTESt:FUNCtion:BUZZer', 'both', maskTest],
		[':MTESt:FUNCtion:COF', 'both', maskTest],
		[':MTESt:FUNCtion:FTH', 'both', maskTest],
		[':MTESt:FUNCtion:SOF', 'both', maskTest],
		[':MTESt:IDISplay', 'both', maskTest],
		[':MTESt:MASK:CREate', 'command', maskCreate],
		[':MTESt:MASK:LOAD', 'command', maskLoad],
		[':MTESt:OPERate', 'both', maskState],
		[':MTESt:RESet', 'command', maskReset],
		[':MTESt:SOURce', 'both', maskTest],
		[':MTESt:TYPE', 'both', maskTest],
	]),
	...subsystem('recall', [
		[':RECall:FDEFault', 'command', setupRecall],
		[':RECall:REFerence', 'command', referenceData],
		[':RECall:SERase', 'command', { ...done('tools/storage', 'erase_internal_storage'), ...destructive }],
		[':RECall:SETup', 'command', setupRecall],
	]),
	...subsystem('ref', [
		[':REF<r>:LABel', 'both', reference],
		[':REF<r>:LABel:TEXT', 'both', reference],
		[':REF<r>:DATA', 'command', referenceData],
		[':REF<r>:DATA:SOURce', 'query', reference],
		[':REF<r>:DATA:SCALe', 'both', reference],
		[':REF<r>:DATA:POSition', 'both', reference],
	]),
	...subsystem('save', [
		[':SAVE:BINary', 'command', waveformFile],
		[':SAVE:CSV', 'command', waveformFile],
		[':SAVE:DEFault', 'command', setupSave],
		[':SAVE:IMAGe', 'command', { ...done('tools/storage', 'save_screenshot'), ...destructive }],
		[':SAVE:MATLab', 'command', waveformFile],
		[':SAVE:REFerence', 'command', waveformFile],
		[':SAVE:SETup', 'command', setupSave],
	]),
	...subsystem('search', [
		[':SEARch', 'both', searchState],
		[':SEARch:MODE', 'both', search],
		[':SEARch:COUNt', 'query', searchEvents],
		[':SEARch:EVENt', 'query', searchEvents],
		[':SEARch:COPY', 'command', searchCopy],
		[':SEARch:EDGE:SOURce', 'both', search],
		[':SEARch:EDGE:SLOPe', 'both', search],
		[':SEARch:EDGE:LEVel', 'both', search],
		[':SEARch:SLOPe:SOURce', 'both', search],
		[':SEARch:SLOPe:SLOPe', 'both', search],
		[':SEARch:SLOPe:HLEVel', 'both', search],
		[':SEARch:SLOPe:LLEVel', 'both', search],
		[':SEARch:SLOPe:LIMit', 'both', search],
		[':SEARch:SLOPe:TUPPer', 'both', search],
		[':SEARch:SLOPe:TLOWer', 'both', search],
		[':SEARch:PULSe:SOURce', 'both', search],
		[':SEARch:PULSe:POLarity', 'both', search],
		[':SEARch:PULSe:LEVel', 'both', search],
		[':SEARch:PULSe:LIMit', 'both', search],
		[':SEARch:PULSe:TUPPer', 'both', search],
		[':SEARch:PULSe:TLOWer', 'both', search],
		[':SEARch:INTerval:SOURce', 'both', search],
		[':SEARch:INTerval:SLOPe', 'both', search],
		[':SEARch:INTerval:LEVel', 'both', search],
		[':SEARch:INTerval:LIMit', 'both', search],
		[':SEARch:INTerval:TUPPer', 'both', search],
		[':SEARch:INTerval:TLOWer', 'both', search],
		[':SEARch:RUNT:SOURce', 'both', search],
		[':SEARch:RUNT:POLarity', 'both', search],
		[':SEARch:RUNT:HLEVel', 'both', search],
		[':SEARch:RUNT:LLEVel', 'both', search],
		[':SEARch:RUNT:LIMit', 'both', search],
		[':SEARch:RUNT:TUPPer', 'both', search],
		[':SEARch:RUNT:TLOWer', 'both', search],
	]),
	...subsystem('system', [
		[':SYSTem:BUZZer', 'both', settings],
		[':SYSTem:CLOCk', 'both', settings],
		[':SYSTem:COMMunicate:LAN:GATeway', 'both', lan],
		[':SYSTem:COMMunicate:LAN:IPADdress', 'both', { ...destructive, ...lan }],
		[':SYSTem:COMMunicate:LAN:MAC', 'query', done('tools/system', 'get_lan_configuration')],
		[':SYSTem:COMMunicate:LAN:SMASk', 'both', lan],
		[':SYSTem:COMMunicate:LAN:TYPE', 'both', { ...destructive, ...lan }],
		[':SYSTem:COMMunicate:VNCPort', 'both', lan],
		[':SYSTem:DATE', 'both', settings],
		[':SYSTem:EDUMode', 'both', settings],
		[':SYSTem:LANGuage', 'both', settings],
		[
			':SYSTem:MENU',
			'both',
			partial(
				done('tools/system', 'configure_system_settings'),
				'The command is written and the query is never sent. The guide documents the query for models with a menu switch alone, nothing in the identity tells those models apart, and on a model without the switch the query would never answer.',
			),
		],
		[':SYSTem:NSTorage', 'both', storage],
		[':SYSTem:NSTorage:CONNect', 'command', done('tools/system', 'configure_network_storage')],
		[':SYSTem:NSTorage:DISConnect', 'command', done('tools/system', 'configure_network_storage')],
		[':SYSTem:NSTorage:STATus', 'query', storage],
		[':SYSTem:PON', 'both', settings],
		[':SYSTem:REBoot', 'command', { ...destructive, ...done('tools/system', 'reboot_scope') }],
		// get_waveform releases the lock the :WAVeform traffic engages on its own, observed on an SDS1204X HD.
		[
			':SYSTem:REMote',
			'both',
			done('tools/system', 'get_system_settings', 'configure_system_settings', 'get_waveform'),
		],
		[':SYSTem:SELFCal', 'both', { ...destructive, ...done('tools/system', 'calibrate_scope', 'get_system_settings') }],
		[':SYSTem:SHUTdown', 'command', { ...destructive, ...done('tools/system', 'shutdown_scope') }],
		[':SYSTem:SSAVer', 'both', settings],
		[':SYSTem:TIME', 'both', settings],
		[':SYSTem:TOUCh', 'both', settings],
	]),
	...subsystem('timebase', [
		[':TIMebase:DELay', 'both', timebase],
		[':TIMebase:REFerence', 'both', timebase],
		[':TIMebase:REFerence:POSition', 'both', timebase],
		[':TIMebase:SCALe', 'both', done('tools/timebase', 'get_timebase', 'configure_timebase', 'get_waveform')],
		[':TIMebase:WINDow', 'both', timebase],
		[':TIMebase:WINDow:DELay', 'both', timebase],
		[':TIMebase:WINDow:SCALe', 'both', timebase],
	]),
	...subsystem('trigger', [
		[':TRIGger:FREQuency', 'query', done('tools/trigger', 'get_trigger')],
		[':TRIGger:MODE', 'both', sweep],
		[':TRIGger:RUN', 'command', runControl],
		[':TRIGger:STATus', 'query', sweep],
		[':TRIGger:STOP', 'command', runControl],
		// All 24 trigger types the command names are selectable: the thirteen non-serial ones of pp. 421-575 and the
		// eleven serial ones of pp. 577-682, two of which (M1553, ARINC429) the guide gives no parameter command.
		[':TRIGger:TYPE', 'both', trigger],
		[':TRIGger:EDGE:COUPling', 'both', trigger],
		[':TRIGger:EDGE:HLDEVent', 'both', trigger],
		[':TRIGger:EDGE:HLDTime', 'both', trigger],
		[':TRIGger:EDGE:HOLDoff', 'both', trigger],
		[':TRIGger:EDGE:HSTart', 'both', trigger],
		[':TRIGger:EDGE:IMPedance', 'both', trigger],
		[':TRIGger:EDGE:LEVel', 'both', trigger],
		[':TRIGger:EDGE:NREJect', 'both', trigger],
		[':TRIGger:EDGE:SLOPe', 'both', trigger],
		[':TRIGger:EDGE:SOURce', 'both', trigger],
		[':TRIGger:SLOPe:COUPling', 'both', trigger],
		[':TRIGger:SLOPe:HLDEVent', 'both', trigger],
		[':TRIGger:SLOPe:HLDTime', 'both', trigger],
		[':TRIGger:SLOPe:HLEVel', 'both', trigger],
		[':TRIGger:SLOPe:HOLDoff', 'both', trigger],
		[':TRIGger:SLOPe:HSTart', 'both', trigger],
		[':TRIGger:SLOPe:LIMit', 'both', trigger],
		[':TRIGger:SLOPe:LLEVel', 'both', trigger],
		[':TRIGger:SLOPe:NREJect', 'both', trigger],
		[':TRIGger:SLOPe:SLOPe', 'both', trigger],
		[':TRIGger:SLOPe:SOURce', 'both', trigger],
		[':TRIGger:SLOPe:TLOWer', 'both', trigger],
		[':TRIGger:SLOPe:TUPPer', 'both', trigger],
		[':TRIGger:PULSe:COUPling', 'both', trigger],
		[':TRIGger:PULSe:HLDEVent', 'both', trigger],
		[':TRIGger:PULSe:HLDTime', 'both', trigger],
		[':TRIGger:PULSe:HOLDoff', 'both', trigger],
		[':TRIGger:PULSe:HSTart', 'both', trigger],
		[':TRIGger:PULSe:LEVel', 'both', trigger],
		[':TRIGger:PULSe:LIMit', 'both', trigger],
		[':TRIGger:PULSe:NREJect', 'both', trigger],
		[':TRIGger:PULSe:POLarity', 'both', trigger],
		[':TRIGger:PULSe:SOURce', 'both', trigger],
		[':TRIGger:PULSe:TLOWer', 'both', trigger],
		[':TRIGger:PULSe:TUPPer', 'both', trigger],
		[':TRIGger:VIDeo:FCNT', 'both', trigger],
		[':TRIGger:VIDeo:FIELd', 'both', trigger],
		[':TRIGger:VIDeo:FRATe', 'both', trigger],
		[':TRIGger:VIDeo:INTerlace', 'both', trigger],
		[':TRIGger:VIDeo:LCNT', 'both', trigger],
		[':TRIGger:VIDeo:LEVel', 'both', trigger],
		[':TRIGger:VIDeo:LINE', 'both', trigger],
		[':TRIGger:VIDeo:SOURce', 'both', trigger],
		[':TRIGger:VIDeo:STANdard', 'both', trigger],
		[':TRIGger:VIDeo:SYNC', 'both', trigger],
		[':TRIGger:WINDow:CLEVel', 'both', trigger],
		[':TRIGger:WINDow:COUPling', 'both', trigger],
		[':TRIGger:WINDow:DLEVel', 'both', trigger],
		[':TRIGger:WINDow:HLDEVent', 'both', trigger],
		[':TRIGger:WINDow:HLDTime', 'both', trigger],
		[':TRIGger:WINDow:HLEVel', 'both', trigger],
		[':TRIGger:WINDow:HOLDoff', 'both', trigger],
		[':TRIGger:WINDow:HSTart', 'both', trigger],
		[':TRIGger:WINDow:LLEVel', 'both', trigger],
		[':TRIGger:WINDow:NREJect', 'both', trigger],
		[':TRIGger:WINDow:SOURce', 'both', trigger],
		[':TRIGger:WINDow:TYPE', 'both', trigger],
		[':TRIGger:INTerval:COUPling', 'both', trigger],
		[':TRIGger:INTerval:HLDEVent', 'both', trigger],
		[':TRIGger:INTerval:HLDTime', 'both', trigger],
		[':TRIGger:INTerval:HOLDoff', 'both', trigger],
		[':TRIGger:INTerval:HSTart', 'both', trigger],
		[':TRIGger:INTerval:LEVel', 'both', trigger],
		[':TRIGger:INTerval:LIMit', 'both', trigger],
		[':TRIGger:INTerval:NREJect', 'both', trigger],
		[':TRIGger:INTerval:SLOPe', 'both', trigger],
		[':TRIGger:INTerval:SOURce', 'both', trigger],
		[':TRIGger:INTerval:TLOWer', 'both', trigger],
		[':TRIGger:INTerval:TUPPer', 'both', trigger],
		[':TRIGger:DROPout:COUPling', 'both', trigger],
		[':TRIGger:DROPout:HLDEVent', 'both', trigger],
		[':TRIGger:DROPout:HLDTime', 'both', trigger],
		[':TRIGger:DROPout:HOLDoff', 'both', trigger],
		[':TRIGger:DROPout:HSTart', 'both', trigger],
		[':TRIGger:DROPout:LEVel', 'both', trigger],
		[':TRIGger:DROPout:NREJect', 'both', trigger],
		[':TRIGger:DROPout:SLOPe', 'both', trigger],
		[':TRIGger:DROPout:SOURce', 'both', trigger],
		[':TRIGger:DROPout:TIME', 'both', trigger],
		[':TRIGger:DROPout:TYPE', 'both', trigger],
		[':TRIGger:RUNT:COUPling', 'both', trigger],
		[':TRIGger:RUNT:HLDEVent', 'both', trigger],
		[':TRIGger:RUNT:HLDTime', 'both', trigger],
		[':TRIGger:RUNT:HLEVel', 'both', trigger],
		[':TRIGger:RUNT:HOLDoff', 'both', trigger],
		[':TRIGger:RUNT:HSTart', 'both', trigger],
		[':TRIGger:RUNT:LIMit', 'both', trigger],
		[':TRIGger:RUNT:LLEVel', 'both', trigger],
		[':TRIGger:RUNT:NREJect', 'both', trigger],
		[':TRIGger:RUNT:POLarity', 'both', trigger],
		[':TRIGger:RUNT:SOURce', 'both', trigger],
		[':TRIGger:RUNT:TLOWer', 'both', trigger],
		[':TRIGger:RUNT:TUPPer', 'both', trigger],
		[':TRIGger:PATTern:HLDEVent', 'both', trigger],
		[':TRIGger:PATTern:HLDTime', 'both', trigger],
		[':TRIGger:PATTern:HOLDoff', 'both', trigger],
		[':TRIGger:PATTern:HSTart', 'both', trigger],
		[':TRIGger:PATTern:INPut', 'both', trigger],
		[
			':TRIGger:PATTern:LEVel',
			'both',
			partial(
				trigger,
				'The command is written and the query is never sent. Both forms carry the source as an argument, a shape this driver sends nowhere else, so get_trigger reports the pattern trigger without its per-source level.',
			),
		],
		[':TRIGger:PATTern:LIMit', 'both', trigger],
		[':TRIGger:PATTern:LOGic', 'both', trigger],
		[':TRIGger:PATTern:TLOWer', 'both', trigger],
		[':TRIGger:PATTern:TUPPer', 'both', trigger],
		[':TRIGger:QUALified:ELEVel', 'both', trigger],
		[':TRIGger:QUALified:ESLope', 'both', trigger],
		[':TRIGger:QUALified:ESource', 'both', trigger],
		[':TRIGger:QUALified:LIMit', 'both', trigger],
		[':TRIGger:QUALified:QLEVel', 'both', trigger],
		[':TRIGger:QUALified:QSource', 'both', trigger],
		[':TRIGger:QUALified:TLOWer', 'both', trigger],
		[':TRIGger:QUALified:TUPPer', 'both', trigger],
		[':TRIGger:QUALified:TYPE', 'both', trigger],
		[':TRIGger:DELay:COUPling', 'both', trigger],
		[':TRIGger:DELay:SOURce', 'both', trigger],
		[':TRIGger:DELay:SOURce2', 'both', trigger],
		[':TRIGger:DELay:SLOPe', 'both', trigger],
		[':TRIGger:DELay:SLOPe2', 'both', trigger],
		[
			':TRIGger:DELay:LEVel',
			'both',
			partial(
				trigger,
				'The command is written and the query is never sent, for the same reason as :TRIGger:PATTern:LEVel. get_trigger reports the delay trigger without its per-source level.',
			),
		],
		[':TRIGger:DELay:LEVel2', 'both', trigger],
		[':TRIGger:DELay:LIMit', 'both', trigger],
		[':TRIGger:DELay:TUPPer', 'both', trigger],
		[':TRIGger:DELay:TLOWer', 'both', trigger],
		[':TRIGger:NEDGe:SOURce', 'both', trigger],
		[':TRIGger:NEDGe:SLOPe', 'both', trigger],
		[':TRIGger:NEDGe:IDLE', 'both', trigger],
		[':TRIGger:NEDGe:EDGE', 'both', trigger],
		[':TRIGger:NEDGe:LEVel', 'both', trigger],
		[':TRIGger:NEDGe:HOLDoff', 'both', trigger],
		[':TRIGger:NEDGe:HLDTime', 'both', trigger],
		[':TRIGger:NEDGe:HLDEVent', 'both', trigger],
		[':TRIGger:NEDGe:HSTart', 'both', trigger],
		[':TRIGger:NEDGe:NREJect', 'both', trigger],
		[':TRIGger:SHOLd:TYPE', 'both', trigger],
		[':TRIGger:SHOLd:CSource', 'both', trigger],
		[':TRIGger:SHOLd:CTHReshold', 'both', trigger],
		[':TRIGger:SHOLd:SLOPe', 'both', trigger],
		[':TRIGger:SHOLd:DSource', 'both', trigger],
		[':TRIGger:SHOLd:DTHReshold', 'both', trigger],
		[':TRIGger:SHOLd:LEVel', 'both', trigger],
		[':TRIGger:SHOLd:LIMit', 'both', trigger],
		[':TRIGger:SHOLd:TUPPer', 'both', trigger],
		[':TRIGger:SHOLd:TLOWer', 'both', trigger],
		[':TRIGger:IIC:ADDRess', 'both', trigger],
		[':TRIGger:IIC:ALENgth', 'both', trigger],
		[':TRIGger:IIC:CONDition', 'both', trigger],
		[':TRIGger:IIC:DAT2', 'both', trigger],
		[':TRIGger:IIC:DATA', 'both', trigger],
		[':TRIGger:IIC:DLENgth', 'both', trigger],
		[':TRIGger:IIC:LIMit', 'both', trigger],
		[':TRIGger:IIC:RWBit', 'both', trigger],
		[':TRIGger:IIC:SCLSource', 'both', trigger],
		[':TRIGger:IIC:SCLThreshold', 'both', trigger],
		[':TRIGger:IIC:SDASource', 'both', trigger],
		[':TRIGger:IIC:SDAThreshold', 'both', trigger],
		[':TRIGger:SPI:BITorder', 'both', trigger],
		[':TRIGger:SPI:CLKSource', 'both', trigger],
		[':TRIGger:SPI:CLKThreshold', 'both', trigger],
		[':TRIGger:SPI:CSSource', 'both', trigger],
		[':TRIGger:SPI:CSThreshold', 'both', trigger],
		[':TRIGger:SPI:CSTYpe', 'both', trigger],
		[':TRIGger:SPI:DATA', 'command', trigger],
		[':TRIGger:SPI:DLENgth', 'both', trigger],
		[':TRIGger:SPI:LATChedge', 'both', trigger],
		[':TRIGger:SPI:MISOSource', 'both', trigger],
		[':TRIGger:SPI:MISOThreshold', 'both', trigger],
		[':TRIGger:SPI:MOSISource', 'both', trigger],
		[':TRIGger:SPI:MOSIThreshold', 'both', trigger],
		[':TRIGger:SPI:NCSSource', 'both', trigger],
		[':TRIGger:SPI:NCSThreshold', 'both', trigger],
		[':TRIGger:SPI:TTYPe', 'both', trigger],
		[':TRIGger:UART:BAUD', 'both', trigger],
		[':TRIGger:UART:BITorder', 'both', trigger],
		[':TRIGger:UART:CONDition', 'both', trigger],
		[':TRIGger:UART:DATA', 'both', trigger],
		[':TRIGger:UART:DLENgth', 'both', trigger],
		[':TRIGger:UART:IDLE', 'both', trigger],
		[':TRIGger:UART:LIMit', 'both', trigger],
		[':TRIGger:UART:PARity', 'both', trigger],
		[':TRIGger:UART:RXSource', 'both', trigger],
		[':TRIGger:UART:RXThreshold', 'both', trigger],
		[':TRIGger:UART:STOP', 'both', trigger],
		[':TRIGger:UART:TTYPe', 'both', trigger],
		[':TRIGger:UART:TXSource', 'both', trigger],
		[':TRIGger:UART:TXThreshold', 'both', trigger],
		[':TRIGger:CAN:BAUD', 'both', trigger],
		[':TRIGger:CAN:CONDition', 'both', trigger],
		[':TRIGger:CAN:DAT2', 'both', trigger],
		[':TRIGger:CAN:DATA', 'both', trigger],
		[':TRIGger:CAN:ID', 'both', trigger],
		[':TRIGger:CAN:IDLength', 'both', trigger],
		[':TRIGger:CAN:SOURce', 'both', trigger],
		[':TRIGger:CAN:THReshold', 'both', trigger],
		[':TRIGger:LIN:BAUD', 'both', trigger],
		[':TRIGger:LIN:CONDition', 'both', trigger],
		[':TRIGger:LIN:DAT2', 'both', trigger],
		[':TRIGger:LIN:DATA', 'both', trigger],
		[':TRIGger:LIN:ERRor:CHECksum', 'both', trigger],
		[':TRIGger:LIN:ERRor:DLENgth', 'both', trigger],
		[':TRIGger:LIN:ERRor:ID', 'both', trigger],
		[':TRIGger:LIN:ERRor:PARity', 'both', trigger],
		[':TRIGger:LIN:ERRor:SYNC', 'both', trigger],
		[':TRIGger:LIN:ID', 'both', trigger],
		[':TRIGger:LIN:SOURce', 'both', trigger],
		[':TRIGger:LIN:STANdard', 'both', trigger],
		[':TRIGger:LIN:THReshold', 'both', trigger],
		[':TRIGger:FLEXray:BAUD', 'both', trigger],
		[':TRIGger:FLEXray:CONDition', 'both', trigger],
		[':TRIGger:FLEXray:FRAMe:COMPare', 'both', trigger],
		[':TRIGger:FLEXray:FRAMe:CYCLe', 'both', trigger],
		[':TRIGger:FLEXray:FRAMe:ID', 'both', trigger],
		[':TRIGger:FLEXray:FRAMe:REPetition', 'both', trigger],
		[':TRIGger:FLEXray:SOURce', 'both', trigger],
		[':TRIGger:FLEXray:THReshold', 'both', trigger],
		[':TRIGger:CANFd:BAUDData', 'both', trigger],
		[':TRIGger:CANFd:BAUDNominal', 'both', trigger],
		[':TRIGger:CANFd:CONDition', 'both', trigger],
		[':TRIGger:CANFd:DAT2', 'both', trigger],
		[':TRIGger:CANFd:DATA', 'both', trigger],
		[':TRIGger:CANFd:FTYPe', 'both', trigger],
		[':TRIGger:CANFd:ID', 'both', trigger],
		[':TRIGger:CANFd:IDLength', 'both', trigger],
		[':TRIGger:CANFd:SOURce', 'both', trigger],
		[':TRIGger:CANFd:THReshold', 'both', trigger],
		[':TRIGger:IIS:AVARiant', 'both', trigger],
		[':TRIGger:IIS:BCLKSource', 'both', trigger],
		[':TRIGger:IIS:BCLKThreshold', 'both', trigger],
		[':TRIGger:IIS:BITorder', 'both', trigger],
		[':TRIGger:IIS:CHANnel', 'both', trigger],
		[':TRIGger:IIS:COMPare', 'both', trigger],
		[':TRIGger:IIS:CONDition', 'both', trigger],
		[':TRIGger:IIS:DLENgth', 'both', trigger],
		[':TRIGger:IIS:DSource', 'both', trigger],
		[':TRIGger:IIS:DTHReshold', 'both', trigger],
		[':TRIGger:IIS:BCLK:EDGE', 'both', trigger],
		[':TRIGger:IIS:LCH', 'both', trigger],
		[':TRIGger:IIS:VALue', 'both', trigger],
		[':TRIGger:IIS:WSSource', 'both', trigger],
		[':TRIGger:IIS:WSTHreshold', 'both', trigger],
		[':TRIGger:SENT:SOURce', 'both', trigger],
		[':TRIGger:SENT:THReshold', 'both', trigger],
	]),
	...subsystem('waveform', [
		[
			':WAVeform:SOURce',
			'both',
			partial(
				waveform,
				'The guide documents C<n>, F<x> and D<d>. Analog channels and math functions are written and digital lines are refused, because a digital block counts points rather than bytes and needs the MSO option, which nothing in the identity reports.',
			),
		],
		[':WAVeform:STARt', 'both', waveform],
		[':WAVeform:INTerval', 'both', waveform],
		[':WAVeform:POINt', 'both', waveform],
		[':WAVeform:MAXPoint', 'query', waveform],
		[':WAVeform:WIDTh', 'both', waveform],
		[':WAVeform:PREamble', 'query', { ...waveform, response: 'binary' }],
		[':WAVeform:DATA', 'query', { ...waveform, response: 'binary' }],
		[':WAVeform:SEQuence', 'both', waveform],
	]),
	...subsystem('wgen', [
		['C1:ARbWaVe', 'both', generator],
		['C1:BaSic_WaVe', 'both', generator],
		['C1:OUTPut', 'both', { ...generator, ...destructive }],
		['SToreList', 'query', generatorStore],
		['C1:SYNC', 'both', generator],
		['VOLTPRT', 'both', generator],
	]),
	...subsystem('meter', [
		['MMETer', 'command', meter],
		['READ', 'query', meterValue],
		['CONFigure', 'query', meterFunction],
		['CONFigure:CONTinuity', 'command', meter],
		['CONFigure:CURRent:AC', 'command', meter],
		['CONFigure:CURRent:DC', 'command', meter],
		['CONFigure:DIODe', 'command', meter],
		['CONFigure:RESistance', 'command', meter],
		['CONFigure[:VOLTage]:AC', 'command', meter],
		['CONFigure[:VOLTage]:DC', 'command', meter],
		['CONFigure:CAPacitance', 'command', meter],
		['MEASure:CONTinuity', 'query', meterMeasure],
		['MEASure:CURRent:AC', 'query', meterMeasure],
		['MEASure:CURRent:DC', 'query', meterMeasure],
		['MEASure:DIODe', 'query', meterMeasure],
		['MEASure:RESistance', 'query', meterMeasure],
		['MEASure[:VOLTage]:AC', 'query', meterMeasure],
		['MEASure[:VOLTage]:DC', 'query', meterMeasure],
		['MEASure:CAPacitance', 'query', meterMeasure],
		['[SENSe:]CURRent:AC:NULL', 'command', meter],
		['[SENSe:]CURRent:DC:NULL', 'command', meter],
		['[SENSe:]CURRent:AC:SELEct', 'command', meter],
		['[SENSe:]CURRent:DC:SELEct', 'command', meter],
		['[SENSe:]RESistance:NULL', 'command', meter],
		['[SENSe:]VOLTage:AC:NULL', 'command', meter],
		['[SENSe:]VOLTage:DC:NULL', 'command', meter],
		['[SENSe:]VOLTage:AC:SELEct', 'command', meter],
		['[SENSe:]VOLTage:DC:SELEct', 'command', meter],
		['[SENSe:]CAPacitance:NULL', 'command', meter],
	]),
];
