// One request per serial trigger type, writing every parameter the guide gives that bus, next to the exact lines it
// has to put on the wire. Cross-protocol copy-paste is the failure mode these buses invite, so the mnemonics are
// spelled out here rather than derived, and the conformance fixtures drive the same requests.
export interface SerialCase {
	input: Record<string, unknown>;
	commands: string[];
}

export const serialTriggers: SerialCase[] = [
	{
		input: {
			type: 'IIC',
			clock_source: 'C1',
			clock_threshold: 1.5,
			data_source: 'C2',
			data_threshold: 1.5,
			address_length: '7BIT',
			data_length: 12,
			condition: 'EEPRom',
			address: 80,
			direction: 'READ',
			compare: 'EQUal',
			data: 255,
			data2: 256,
		},
		commands: [
			':TRIGger:TYPE IIC',
			':TRIGger:IIC:SCLSource C1',
			':TRIGger:IIC:SCLThreshold 1.50E+00',
			':TRIGger:IIC:SDASource C2',
			':TRIGger:IIC:SDAThreshold 1.50E+00',
			':TRIGger:IIC:ALENgth 7BIT',
			':TRIGger:IIC:DLENgth 12',
			':TRIGger:IIC:CONDition EEPRom',
			':TRIGger:IIC:ADDRess 80',
			':TRIGger:IIC:RWBit READ',
			':TRIGger:IIC:LIMit EQUal',
			':TRIGger:IIC:DATA 255',
			':TRIGger:IIC:DAT2 256',
		],
	},
	{
		input: {
			type: 'SPI',
			clock_source: 'C1',
			clock_threshold: 1.5,
			mosi_source: 'C2',
			mosi_threshold: 1.5,
			miso_source: 'C3',
			miso_threshold: 1.5,
			cs_source: 'C4',
			cs_threshold: 1.5,
			ncs_source: 'D0',
			ncs_threshold: 1.5,
			cs_type: 1e-6,
			latch_edge: 'RISing',
			bit_order: 'MSB',
			trigger_on: 'MOSI',
			data_length: 8,
			data_pattern: ['1', '0', '0', '0', '0', '0', '1', '0'],
		},
		commands: [
			':TRIGger:TYPE SPI',
			':TRIGger:SPI:CLKSource C1',
			':TRIGger:SPI:CLKThreshold 1.50E+00',
			':TRIGger:SPI:MOSISource C2',
			':TRIGger:SPI:MOSIThreshold 1.50E+00',
			':TRIGger:SPI:MISOSource C3',
			':TRIGger:SPI:MISOThreshold 1.50E+00',
			':TRIGger:SPI:CSSource C4',
			':TRIGger:SPI:CSThreshold 1.50E+00',
			':TRIGger:SPI:NCSSource D0',
			':TRIGger:SPI:NCSThreshold 1.50E+00',
			':TRIGger:SPI:CSTYpe TIMeout,1.00E-06',
			':TRIGger:SPI:LATChedge RISing',
			':TRIGger:SPI:BITorder MSB',
			':TRIGger:SPI:TTYPe MOSI',
			':TRIGger:SPI:DLENgth 8',
			':TRIGger:SPI:DATA 1,0,0,0,0,0,1,0',
		],
	},
	{
		input: {
			type: 'UART',
			rx_source: 'C1',
			rx_threshold: 1.5,
			tx_source: 'C2',
			tx_threshold: 1.5,
			baud: '9600bps',
			bit_order: 'LSM',
			parity: 'EVEN',
			stop_bits: 1.5,
			idle_level: 'HIGH',
			data_length: 8,
			trigger_on: 'RX',
			condition: 'DATA',
			compare: 'EQUal',
			data: 255,
		},
		commands: [
			':TRIGger:TYPE UART',
			':TRIGger:UART:RXSource C1',
			':TRIGger:UART:RXThreshold 1.50E+00',
			':TRIGger:UART:TXSource C2',
			':TRIGger:UART:TXThreshold 1.50E+00',
			':TRIGger:UART:BAUD 9600bps',
			':TRIGger:UART:BITorder LSM',
			':TRIGger:UART:PARity EVEN',
			':TRIGger:UART:STOP 1.5',
			':TRIGger:UART:IDLE HIGH',
			':TRIGger:UART:DLENgth 8',
			':TRIGger:UART:TTYPe RX',
			':TRIGger:UART:CONDition DATA',
			':TRIGger:UART:LIMit EQUal',
			':TRIGger:UART:DATA 255',
		],
	},
	{
		input: {
			type: 'CAN',
			source: 'C1',
			threshold: 1.5,
			baud: 500_000,
			id_length: '29BITS',
			condition: 'ID_AND_DATA',
			id: 1234,
			data: 255,
			data2: 256,
		},
		commands: [
			':TRIGger:TYPE CAN',
			':TRIGger:CAN:SOURce C1',
			':TRIGger:CAN:THReshold 1.50E+00',
			':TRIGger:CAN:BAUD CUSTom,500000',
			':TRIGger:CAN:IDLength 29BITS',
			':TRIGger:CAN:CONDition ID_AND_DATA',
			':TRIGger:CAN:ID 1234',
			':TRIGger:CAN:DATA 255',
			':TRIGger:CAN:DAT2 256',
		],
	},
	{
		input: {
			type: 'CANFd',
			source: 'C1',
			threshold: 1.5,
			baud: '1Mbps',
			data_baud: '5Mbps',
			frame_type: 'CANFd',
			id_length: '11BITS',
			condition: 'ID',
			id: 1024,
			data: 255,
			data2: 256,
		},
		commands: [
			':TRIGger:TYPE CANFd',
			':TRIGger:CANFd:SOURce C1',
			':TRIGger:CANFd:THReshold 1.50E+00',
			':TRIGger:CANFd:BAUDNominal 1Mbps',
			':TRIGger:CANFd:BAUDData 5Mbps',
			':TRIGger:CANFd:FTYPe CANFd',
			':TRIGger:CANFd:IDLength 11BITS',
			':TRIGger:CANFd:CONDition ID',
			':TRIGger:CANFd:ID 1024',
			':TRIGger:CANFd:DATA 255',
			':TRIGger:CANFd:DAT2 256',
		],
	},
	{
		input: {
			type: 'LIN',
			source: 'C1',
			threshold: 1.5,
			baud: '19200bps',
			condition: 'DATA_ERROR',
			id: 64,
			data: 255,
			data2: 256,
			checksum_error: true,
			parity_error: false,
			sync_error: true,
			lin_standard: 1,
			error_id: 63,
			data_length: 8,
		},
		commands: [
			':TRIGger:TYPE LIN',
			':TRIGger:LIN:SOURce C1',
			':TRIGger:LIN:THReshold 1.50E+00',
			':TRIGger:LIN:BAUD 19200bps',
			':TRIGger:LIN:CONDition DATA_ERROR',
			':TRIGger:LIN:ID 64',
			':TRIGger:LIN:DATA 255',
			':TRIGger:LIN:DAT2 256',
			':TRIGger:LIN:ERRor:CHECksum 1',
			':TRIGger:LIN:ERRor:PARity 0',
			':TRIGger:LIN:ERRor:SYNC 1',
			':TRIGger:LIN:STANdard 1',
			':TRIGger:LIN:ERRor:ID 63',
			':TRIGger:LIN:ERRor:DLENgth 8',
		],
	},
	{
		input: {
			type: 'FLEXray',
			source: 'C1',
			threshold: 1.5,
			baud: '10Mbps',
			condition: 'FRAMe',
			id: 2048,
			compare: 'EQUal',
			frame_cycle: 63,
			repetition: 64,
		},
		commands: [
			':TRIGger:TYPE FLEXray',
			':TRIGger:FLEXray:SOURce C1',
			':TRIGger:FLEXray:THReshold 1.50E+00',
			':TRIGger:FLEXray:BAUD 10Mbps',
			':TRIGger:FLEXray:CONDition FRAMe',
			':TRIGger:FLEXray:FRAMe:ID 2048',
			':TRIGger:FLEXray:FRAMe:COMPare EQUal',
			':TRIGger:FLEXray:FRAMe:CYCLe 63',
			':TRIGger:FLEXray:FRAMe:REPetition 64',
		],
	},
	{
		input: {
			type: 'IIS',
			clock_source: 'C1',
			clock_threshold: 1.5,
			ws_source: 'C2',
			ws_threshold: 1.5,
			data_source: 'C3',
			data_threshold: 1.5,
			audio_variant: 'LJ',
			latch_edge: 'FALLing',
			bit_order: 'MSB',
			left_level: 'LOW',
			audio_channel: 'RIGHT',
			data_length: 32,
			condition: 'DATA',
			compare: 'GREaterthan',
			value: 65_535,
		},
		commands: [
			':TRIGger:TYPE IIS',
			':TRIGger:IIS:BCLKSource C1',
			':TRIGger:IIS:BCLKThreshold 1.50E+00',
			':TRIGger:IIS:WSSource C2',
			':TRIGger:IIS:WSTHreshold 1.50E+00',
			':TRIGger:IIS:DSource C3',
			':TRIGger:IIS:DTHReshold 1.50E+00',
			':TRIGger:IIS:AVARiant LJ',
			':TRIGger:IIS:BCLK:EDGE FALLing',
			':TRIGger:IIS:BITorder MSB',
			':TRIGger:IIS:LCH LOW',
			':TRIGger:IIS:CHANnel RIGHT',
			':TRIGger:IIS:DLENgth 32',
			':TRIGger:IIS:CONDition DATA',
			':TRIGger:IIS:COMPare GREaterthan',
			':TRIGger:IIS:VALue 65535',
		],
	},
	{
		input: { type: 'SENT', source: 'C1', threshold: 1.5 },
		commands: [':TRIGger:TYPE SENT', ':TRIGger:SENT:SOURce C1', ':TRIGger:SENT:THReshold 1.50E+00'],
	},
	{ input: { type: 'M1553' }, commands: [':TRIGger:TYPE M1553'] },
	{ input: { type: 'ARINC429' }, commands: [':TRIGger:TYPE ARINC429'] },
];

// The guide gives :TRIGger:SPI:DATA no query form, so it is the one line above that is written and never read back.
export const readBacks = ({ commands }: SerialCase): string[] =>
	commands.map((line) => `${line.split(' ')[0]}?`).filter((line) => line !== ':TRIGger:SPI:DATA?');
